app/urls.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-

from django.conf import settings
from django.conf.urls import patterns
from django.conf.urls import include
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Home
    url(
        r'^$',
        'app.views.home',
        name='home',
    ),

    url(
        r'^OnlineStoreAdmin/',
        include(admin.site.urls)
    ),

    # url(
    #     r'^accounts/',
    #     include('userprofile.backends.default.urls')
    # ),

    # url(
    #     r'^accounts/',
    #     include('userprofile.urls', namespace='userprofile')
    # ),

    # url(
    #     r'^cart/',
    #     include('cart.urls', namespace='cart')
    # ),

    # url(
    #     r'^',
    #     include('store.urls', namespace='store')
    # ),
)

# Static content for development
urlpatterns += staticfiles_urlpatterns()

# Serve media for development
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-
from django.conf.urls import patterns
from django.conf.urls import url

urlpatterns = patterns(
    'store.views',

    # Create store
    url(
        r'^store_create/$',
        'store_create',
        name='store-create',
    ),

    # Store detail
    url(
        r'^(?P<slug>[-\w]+)/$',
        'store_detail',
        name='store-detail',
    ),

    # Update store
    url(
        r'^(?P<slug>[-\w]+)/edit/$',
        'store_update',
        name='store-update',
    ),

    # Update store image
    url(
        r'^image_store/(?P<slug>[-\w]+)/$',
        'upload_store_image',
        name='upload-store-image',
    ),

    # Create product
    url(
        r'^(?P<slug>[-\w]+)/product/create/$',
        'product_create',
        name='product-create',
    ),

    # Update product
    url(
        r'^(?P<slug>[-\w]+)/product/(?P<product_slug>[-\w]+)/edit/$',
        'product_update',
        name='product-update',
    ),

    # Update product image
    url(
        r'^image_product/(?P<slug>[-\w]+)/$',
        'upload_product_image',
        name='upload-product-image',
    ),

    # Product detail
    url(
        r'^(?P<slug>[-\w]+)/product/(?P<product_slug>[-\w]+)/$',
        'product_detail',
        name='product-detail',
    ),

    # Products by category
    url(
        r'^category/(?P<category>[-\w]+)/$',
        'products_by_category',
        name='products_by_category',
    ),

    # Delete a product
    url(
        r'^(?P<slug>[-\w]+)/product/(?P<product_slug>[-\w]+)/delete/$',
        'delete_product',
        name='delete_product',
    ),
)

store/models.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-
from django.db import models

from autoslug import AutoSlugField


class Store(models.Model):
    """This model represent a store in platform
    """
    name = models.CharField(
        max_length=50,
    )

    description = models.TextField(
        max_length=250,
    )

    logo = models.ImageField(
        upload_to='uploads/logos',
        default='img/logo_default.png',
        blank=True,
    )

    phone = models.CharField(
        max_length=10,
    )

    address = models.CharField(
        max_length=50,
    )

    slug = AutoSlugField(
        unique=True,
        always_update=True,
        populate_from=lambda instance: instance.name,
    )

    created_by = models.ForeignKey(
        'auth.User',
        null=True,
    )

    created_at = models.DateTimeField(
        auto_now_add=True,
    )

    @models.permalink
    def get_absolute_url(self):
        return ('store:store-detail', [self.slug])

    def __unicode__(self):
        return u'{0}'.format(self.name)


class Product(models.Model):
    """This model represent a product in a store.
    """
    name = models.CharField(
        max_length=50,
    )

    category = models.ForeignKey(
        'store.Category',
        null=True,
    )

    quantity = models.PositiveIntegerField(
        default=1,
    )

    description = models.TextField(
        max_length=250,
    )

    image = models.ImageField(
        upload_to='uploads/product_images',
        default='img/logo_default.png',
        blank=True,
    )

    store = models.ForeignKey(
        'store.Store',
        blank=True,
        null=True,
    )

    price = models.PositiveIntegerField(
        verbose_name=u'Price',
    )

    slug = AutoSlugField(
        unique=True,
        always_update=True,
        populate_from=lambda instance: instance.name,
    )

    created_by = models.ForeignKey(
        'auth.User',
        null=True,
    )

    created_at = models.DateTimeField(
        auto_now_add=True,
    )

    @models.permalink
    def get_absolute_url(self):
        return ('store:product-detail', [self.store.slug, self.slug])

    def __unicode__(self):
        return u'{0}'.format(self.name)


class Category(models.Model):
    """This model represent a category for product.
    """
    name = models.CharField(
        max_length=50,
    )

    image = models.ImageField(
        upload_to='uploads/category_images',
        default='img/logo_default.png',
        blank=True,
    )

    slug = AutoSlugField(
        unique=True,
        always_update=True,
        populate_from=lambda instance: instance.name,
    )

    def __unicode__(self):
        return u'{0}'.format(self.name)

store/forms.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-
from django import forms

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit

from store.models import Store
from store.models import Product


class StoreForm(forms.ModelForm):
    class Meta:
        model = Store
        fields = (
            'name',
            'description',
            'logo',
            'phone',
            'address',
        )

    def __init__(self, *args, **kwargs):
        super(StoreForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()

        self.helper.add_input(
            Submit(
                'submit',
                'Create store',
            ),
        )


class ProductForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = (
            'name',
            'description',
            'quantity',
            'category',
            'image',
            'price',
        )

    def __init__(self, *args, **kwargs):
        super(ProductForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()

        self.helper.add_input(
            Submit(
                'submit',
                'Create product',
            ),
        )


class StoreUpdateForm(forms.ModelForm):
    class Meta:
        model = Store
        fields = (
            'name',
            'description',
            'phone',
            'address',
        )

    def __init__(self, *args, **kwargs):
        super(StoreUpdateForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()

        self.helper.add_input(
            Submit(
                'submit',
                'Update store',
            ),
        )


class ProductUpdateForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = (
            'name',
            'description',
            'quantity',
            'category',
            'price',
        )

    def __init__(self, *args, **kwargs):
        super(ProductUpdateForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()

        self.helper.add_input(
            Submit(
                'submit',
                'Update product',
            ),
        )

class UploadImageProductForm(forms.ModelForm):
    """Form to handle the upload of product images
    """
    class Meta:
        model = Product
        fields = ('image',)


class UploadImageStoreForm(forms.ModelForm):
    """Form to handle the upload of product images
    """
    class Meta:
        model = Store
        fields = ('logo',)

store/views.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-

from django.contrib.auth.decorators import login_required
from django.contrib.sites.models import Site
from django.core.urlresolvers import reverse
from django.http import Http404
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.core.exceptions import ObjectDoesNotExist

from store.forms import StoreForm
from store.forms import ProductForm
from store.forms import ProductUpdateForm
from store.forms import StoreUpdateForm
from store.forms import UploadImageProductForm
from store.forms import UploadImageStoreForm
from store.models import Store
from store.models import Product


@login_required
def store_create(request):
    """This view show and process store form
    """
    try:
        store = Store.objects.get(created_by=request.user)
    except ObjectDoesNotExist:
        store = False

    if store:
        raise Http404

    if request.method == 'POST':
        form = StoreForm(
            request.POST,
            request.FILES
        )

        if form.is_valid():
            new_store = form.save()
            new_store.created_by = request.user
            new_store.save()

            return HttpResponseRedirect(
                reverse('userprofile:dashboard')
            )
    else:
        form = StoreForm()

    return render(request, 'store_create.html', {
        'form': form,
    })


@login_required
def store_update(request, slug):
    """This view update the info store.
    """
    store = Store.objects.get(slug=slug)

    if store.created_by != request.user:
        raise Http404

    if request.method == 'POST':
        form = StoreUpdateForm(
            request.POST,
            request.FILES
        )

        if form.is_valid():
            store = Store.objects.get(slug=slug)
            store.name = form.cleaned_data['name']
            store.description = form.cleaned_data['description']
            store.phone = form.cleaned_data['phone']
            store.address = form.cleaned_data['address']
            store.save()
            store = Store.objects.get(id=store.id)

            return HttpResponseRedirect(
                reverse('store:store-detail', args=[store.slug])
            )
    else:
        store = Store.objects.get(slug=slug)
        form = StoreUpdateForm(
            initial={
                'name': store.name,
                'description': store.description,
                'phone': store.phone,
                'address': store.address,
            }
        )

    return render(request, 'store_update.html', {
        'form': form,
        'store': store,
    })


def store_detail(request, slug):
    """This view process the store detail,
    showing the products and info related
    """
    try:
        store = Store.objects.get(slug=slug)
    except ObjectDoesNotExist:
        raise Http404
    products_list = Product.objects.filter(store=store).exclude(quantity__lte=0)
    return render(request, 'store_detail.html', {
        'store': store,
        'products_list': products_list,
        'slug': slug,
    })


@login_required
def product_create(request, slug):
    """This view create a new product.
    """
    if request.method == 'POST':
        form = ProductForm(
            request.POST,
            request.FILES
        )

        if form.is_valid():
            new_product = form.save()
            new_product.store = Store.objects.get(slug=slug)
            new_product.created_by = request.user
            new_product.save()

            return HttpResponseRedirect(
                reverse('store:store-detail', args=[slug])
            )
    else:
        form = ProductForm()

    return render(request, 'product_create.html', {
        'form': form,
    })


@login_required
def product_update(request, slug, product_slug):
    """This view update the info product.
    """
    try:
        product = Product.objects.get(slug=product_slug)
    except ObjectDoesNotExist:
        raise Http404

    if product.created_by != request.user:
        raise Http404

    if request.method == 'POST':
        form = ProductUpdateForm(
            request.POST,
            request.FILES
        )

        if form.is_valid():
            product.name = form.cleaned_data['name']
            product.description = form.cleaned_data['description']
            product.quantity = form.cleaned_data['quantity']
            product.category = form.cleaned_data['category']
            product.price = form.cleaned_data['price']
            product.save()
            return HttpResponseRedirect(
                reverse('store:product-detail', args=[slug, product.slug])
            )
    else:
        form = ProductUpdateForm(
            instance=product,
        )

    return render(request, 'product_update.html', {
        'form': form,
        'product': product,
    })


def product_detail(request, slug, product_slug):
    """This view show the detail product info
    """
    try:
        product = Product.objects.get(slug=product_slug)
    except ObjectDoesNotExist:
        raise Http404

    if product.quantity <= 0:
        raise Http404

    current_site = Site.objects.get_current()

    return render(request, 'product_detail.html', {
        'product': product,
        'slug': slug,
        'current_site': current_site,
    })


@login_required
def upload_product_image(request, slug):
    """Process the uploads for images to product
    """
    if request.method == 'POST':
        product = Product.objects.get(slug=slug)
        uploadform = UploadImageProductForm(
            request.POST, request.FILES, instance=product,
        )
        if uploadform.is_valid():
            uploadform.save()

        return HttpResponseRedirect(
            reverse('store:product-update', args=[product.store.slug, product.slug])
        )

    raise Http404


@login_required
def upload_store_image(request, slug):
    """Process the uploads for images to store
    """
    if request.method == 'POST':
        store = Store.objects.get(slug=slug)
        uploadform = UploadImageStoreForm(
            request.POST, request.FILES, instance=store,
        )
        if uploadform.is_valid():
            uploadform.save()

        return HttpResponseRedirect(
            reverse('store:store-update', args=[store.slug])
        )

    raise Http404

def products_by_category(request, category):
    """This view show the products by category
    """
    products_list = Product.objects.filter(category__slug=category)
    if not products_list:
        raise Http404
    return render(request, 'products_by_category.html', {
        'products_list': products_list,
        'category': category,
        }
    )

@login_required
def delete_product(request, slug, product_slug):
    """This view delete a product selected by slug
    """
    try:
        product = Product.objects.get(slug=product_slug)
    except ObjectDoesNotExist:
        raise Http404

    if product.created_by != request.user:
        raise Http404

    product.delete()

    return HttpResponseRedirect(
        reverse('store:store-detail', args=[slug])
    )

store/templates/product_create.html
{% extends 'layout/base.html' %}
{% load crispy_forms_tags %}

{% block main_content %}
<h2>Crear producto</h2>
{% crispy form %}
{% endblock main_content %}

store/templates/product_detail.html
{% extends 'layout/base.html' %}
{% load thumbnail %}

{% block title %}{{ product.name }}{% endblock title %}

{% block main_content %}

<ul class="breadcrumb">
    <li><a href="{% url 'home' %}">Home</a> <span class="divider">/</span></li>
    <li><a href="{{ product.store.get_absolute_url }}">{{ product.store.name }}</a> <span class="divider">/</span></li>
    <li class="active">{{ product.name }}</li>
</ul>

<div class="span9 post">
	<h2 class="page-header"><span>{{ product.name }}</span></h2>
	<div class="sidebar-line"><span></span></div>                    
<div class="row-fluid product-info">
    <div class="span7">
        <div class="cf">
            <span class="productwrap"><img id="demo4" src="{{ product.image|thumbnail_url:'avatar_273' }}" /></span>
		</div>
	</div>

    <div class="span5">
        <h2 class="post-title">{{ product.name }}</h2>
    	<p>{{ product.description }}</p>
   
        <div class="price">
            <span class="price-new">${{ product.price }}</span>
            <br>
        </div>
        <div class="row-fluid">            
            <div class="span6">
                <a id="add_to_cart" class="btn btn-general" title="Add to Cart" data-code="{{ product.id }}" data-price="{{ product.price }}">
                <span><i class="icon-shopping-cart"></i> Add to Cart</span>
                </a>
			</div>
        </div>
                    
        <div class="deal-share">
			<!-- AddThis Button BEGIN -->
			<div class="addthis_toolbox addthis_default_style addthis_32x32_style">
			<a class="addthis_button_facebook"></a>
			<a class="addthis_button_twitter"></a>
			<a class="addthis_button_pinterest_share"></a>
			<a class="addthis_button_google_plusone_share"></a>
			<a class="addthis_button_compact"></a><a class="addthis_counter addthis_bubble_style"></a>
			</div>
			<script type="text/javascript">
				var addthis_config = {"data_track_addressbar":true};
				var addthis_share = {templates: {twitter: '{{ product.name }} {{ current_site }}{{ product.get_absolute_url }} (via @)',}}
</script>
			<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-51193bee47b24ad4"></script>
			<!-- AddThis Button END -->
		</div>                    
    </div>
</div>
</div><!-- end post span -->
    
{% endblock main_content %}
{% block left_side %}
<div class="well">
<h2 class="widget-title"><span>{{ product.store.name }}</span></h2>
<div class="sidebar-line"><span></span></div>
<img src="{{ product.store.logo|thumbnail_url:'avatar_140' }}" alt="{{ store.name }}" />
    <br>
    {{ product.store.description }}
    <br>
    {{ product.store.phone }}
    <br>
    {{ product.store.address }}
	{% if user.is_authenticated %}
	{% if product.created_by == user %}
	<p>
		<a href="{% url 'store:product-update' slug product.slug %}" class="btn btn-primary">Actualizar informacion del producto</a>
		<a href="{% url 'store:delete_product' slug product.slug %}" class="btn btn-general">Elimnar producto</a>
	</p>
	{% endif %}
	{% endif %}
</div>
{% endblock left_side %}

store/templates/product_update.html
{% extends 'layout/base.html' %}
{% load crispy_forms_tags thumbnail staticfiles %}

{% block main_content %}
<h2>Actualizar información del producto</h2>
<div class="data_product">
    <div class="image_container">
        <img src="{{ product.image|thumbnail_url:'avatar_140' }}" title="image" alt="image"/>
        <form style="display:none;" action="{% url 'store:upload-product-image' product.slug %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <input id="id_logo" type="file" name="image" />
        </form>
        <h4 class="regular_font add_image">
            <a class="mask_cover" href="#"><span class="change_image"></span>Change</a>
        </h4>
    </div>
</div>
{% crispy form %}
{% endblock main_content %}

{% block js %}
<script type="text/javascript">
$(document).on('ready', function(){
    // show add image when rollover
    $('.data_product img').hover(function () {
        $(this).css({opacity: '0.3', cursor:'pointer'}).parent().find('.add_image').css({opacity: '1', cursor: 'auto'});
    }, function () {
        $(this).css({opacity: '1', cursor:'auto'}).parent().find('.add_image').css({opacity: '0.3', cursor: 'pointer'});
    });
    // Upload file handlers
    $('#id_logo').on('change', function () {
        $(this).parent().submit();
    });
    $('.data_product img').on('click', function() {
        $('#id_logo').click();
    });
});
</script>

{% endblock js %}

store/templates/products_by_category.html
{% extends 'layout/base.html' %}
{% load thumbnail %}
<h4><span>{{ category }}</span></h4>
{% block main_content %}

<ul class="breadcrumb">
    <li><a href="#">Home</a> <span class="divider">/</span></li>
    <li><a href="#">Features</a> <span class="divider">/</span></li>
    <li class="active">Category Template with Grid Style</li>
</ul>
            
<div class="row">

<div class="span9 post">
<h2 class="page-header"><span>Category Template with Grid Style</span></h2>
<div class="sidebar-line"><span></span></div>
    <div class="row-fluid">
    {% for product in products_list %}
    {% if forloop.counter0|divisibleby:"4" %}

            {% if forloop.counter0 != 0 %}
            </div>
            <div class="row-fluid">
            {% endif %}

    {% endif %}
        <div class="span3">
            <div class="wdt-product">
                <div class="wdt-products-wrapper">
                    <div class="wdt-product active show">
                        <a href="{{ product.get_absolute_url }}" title="{{ product.name }}">
                            <img src="{{ product.image|thumbnail_url:'avatar_169' }}" alt="{{ product.name }}" />
                        </a>
                        <h4><a href="{{ product.get_absolute_url }}" title="{{ product.name }}">{{ product.name }}</a></h4>
                        <ul class="rating">
                            <li><i class="star-on"></i></li>
                            <li><i class="star-on"></i></li>
                            <li><i class="star-on"></i></li>
                            <li><i class="star-on"></i></li>
                            <li><i class="star-off"></i></li>
                        </ul>
                            <div class="wdt-pricing">
                                <span class="amount">${{ product.price }}</span>
                            </div>
                        <div class="wdt-cart">
                            <div class="wdt-cart-bar">
                                <a href="product.html" title="Pure Color Leisure"><i class="icon-shopping-cart"></i> Add to basket</a>
                            </div>
                        </div>
                        <div class="wdt-overlay">
                            <span class="amount">${{ product.price }}</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% if forloop.last %}
        </div>
    {% endif %}
    {% endfor %}         
</div><!-- end post span -->


</div>
{% endblock main_content %}

{% block left_side %}
<div class="well">
<h2 class="widget-title"><span>Recent Review Items</span></h2>
<div class="sidebar-line"><span></span></div>
<ul class="reviews-posts">
<li>
    <div class="review-thumbnail">
        <a href="#" title="Permalink to this product" rel="bookmark"><img class="img-polaroid" width="70" src="demo-images/01_sidebar.jpg" alt="" /></a>
    </div><!-- review-thumbnail /-->
        <h3><a href="#" title="Permalink to this product" >Latest review Item</a></h3>  
       
    <ul class="rating">
        <li><i class="star-on"></i></li>
        <li><i class="star-on"></i></li>
        <li><i class="star-on"></i></li>
        <li><i class="star-on"></i></li>
        <li><i class="star-on"></i></li>
    </ul>
</li>

<li>
    <div class="review-thumbnail">
        <a href="#" title="Permalink to this product" rel="bookmark"><img class="img-polaroid" width="70" src="" alt="" /></a>
    </div><!-- review-thumbnail /-->
        <h3><a href="#" title="Permalink to this product" >Latest review Item</a></h3>  
       
    <ul class="rating">
        <li><i class="star-on"></i></li>
        <li><i class="star-on"></i></li>
        <li><i class="star-on"></i></li>
        <li><i class="star-off"></i></li>
        <li><i class="star-off"></i></li>
    </ul>
</li>

<li>
    <div class="review-thumbnail">
        <a href="#" title="Permalink to this product" rel="bookmark"><img class="img-polaroid" width="70" src="demo-images/02_sidebar.jpg" alt="" /></a>
    </div><!-- review-thumbnail /-->
        <h3><a href="#" title="Permalink to this product" >Latest review Item</a></h3>  
       
    <ul class="rating">
        <li><i class="star-on"></i></li>
        <li><i class="star-on"></i></li>
        <li><i class="star-on"></i></li>
        <li><i class="star-on"></i></li>
        <li><i class="star-off"></i></li>
    </ul>
</li>
</ul>
</div>

<div class="widget">
<h2 class="widget-title"><span>Site Categories</span></h2>
<div class="sidebar-line"><span></span></div>
    <ul class="bullet_arrow2 categories">
        <li><a href="category-list.html">Woman's</a></li>
        <li><a href="category-list.html">Mans's</a></li>
        <li><a href="category-list.html">Child's</a>
            <ul>
                <li><a href="category-list.html">Bags</a></li>
                <li><a href="category-list.html">Jevellery</a></li>
                <li><a href="category-list.html">Shoes</a></li>
                <li><a href="category-list.html">Shirts</a></li>
            </ul>
        </li>
        <li><a href="category-list.html">Holiday Sale's</a></li>
        <li><a href="category-list.html">Special Promotions</a></li>
        <li><a href="category-list.html">Father Day's</a></li>
        <li><a href="category-list.html">Happy Valentines</a></li>
    </ul>
</div>

<div class="widget">        
<h2 class="widget-title"><span>Advertising</span></h2>
<div class="sidebar-line"><span></span></div>
    <img src="demo-images/01_sidebar-ads.jpg" width="250" alt=""/>
        
    </div>
</div>
{% endblock left_side %}

store/templates/store_create.html
{% extends 'layout/base.html' %}
{% load crispy_forms_tags %}

{% block main_content %}
<h2>Crear tienda</h2>
{% crispy form %}
{% endblock main_content %}

store/templates/store_detail.html
{% extends 'layout/base.html' %}
{% load thumbnail %}

{% block main_content %}

<ul class="breadcrumb">
    <li><a href="{% url 'home' %}">Home</a> <span class="divider">/</span></li>
    <li class="active">{{ store.name }}</li>
</ul>
<h2 class="page-header"><span>Productos ofrecidos por {{ store.name }}</span></h2>
<div class="sidebar-line"><span></span></div>                        
<div class="row-fluid container-folio">
{% if products_list %}
{% for product in products_list %}
<div class="span4">
    <div class="thumbnail">
        <a href="{{ product.get_absolute_url }}">
            <img src="{{ product.image|thumbnail_url:'avatar_273' }}" alt="{{ product.name }}" />
        </a>
        <div class="caption">
        <h3>
            <a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
        </h3>
        <p>
        {{ product.description }}
        </p>
        </div>
    </div>
</div>
{% endfor %}
{% else %}
    Aún no has agregado productos.
</div>
{% endif %}
{% endblock main_content %}
{% block left_side %}
<div class="well">
<h2 class="widget-title"><span>{{ store.name }}</span></h2>
<div class="sidebar-line"><span></span></div>
<img src="{{ store.logo|thumbnail_url:'avatar_140' }}" alt="{{ store.name }}" />
    <br>
    {{ store.description }}
    <br>
    {{ store.phone }}
    <br>
    {{ store.address }}
{% if user.is_authenticated %}
{% if store.created_by == user %}
<p>
<a href="{% url 'store:store-update' slug %}" class="btn btn-primary">Actualizar informacion de tienda</a>
<a href="{% url 'store:product-create' slug %}" class="btn btn-primary">Agregar nuevo producto</a>
</p>
{% endif %}
{% endif %}
</div>
{% endblock left_side %}

store/templates/store_update.html
{% extends 'layout/base.html' %}
{% load crispy_forms_tags thumbnail %}

{% block main_content %}
<h2>Actualizar información de tu tienda.</h2>
<div class="data_store">
    <div class="logo_container">
        <img src="{{ store.logo|thumbnail_url:'avatar_140' }}" title="logo" alt="logo"/>
        <form style="display:none;" action="{% url 'store:upload-store-image' store.slug %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <input id="id_logo" type="file" name="logo" />
        </form>
        <h4 class="regular_font add_logo">
            <a class="mask_cover" href="#"><span class="change_logo"></span>Change</a>
        </h4>
    </div>
</div>
{% crispy form %}
{% endblock main_content %}

{% block js %}
<script type="text/javascript">
$(document).on('ready', function(){
    // show add image when rollover
    $('.data_store img').hover(function () {
        $(this).css({opacity: '0.3', cursor:'pointer'}).parent().find('.add_logo').css({opacity: '1', cursor: 'auto'});
    }, function () {
        $(this).css({opacity: '1', cursor:'auto'}).parent().find('.add_logo').css({opacity: '0.3', cursor: 'pointer'});
    });
    // Upload file handlers
    $('#id_logo').on('change', function () {
        $(this).parent().submit();
    });
    $('.data_store img').on('click', function() {
        $('#id_logo').click();
    });
});
</script>
{% endblock js %}